/*
 *  Copyright 2012-2013 Ontology Engineering Group, Universidad Politecnica de Madrid, Spain

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

/*
 * WidocoGui2.java
 *
 * Created on 16-jun-2014, 21:38:19
 */
package widoco.gui;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import widoco.TextConstants;

/**
 *
 * @author Dani
 */
public class GuiStep2 extends javax.swing.JFrame {
    GuiController g;
    HashMap<String,String> properties;
    
    /** Creates new form WidocoGui2
     * @param g */
    public GuiStep2(GuiController g) {
        this.g =g;
        initComponents();
        Image l = g.getConfig().getLogo().getScaledInstance(widocoLogo.getWidth(), widocoLogo.getHeight(), Image.SCALE_SMOOTH);
        widocoLogo.setIcon(new ImageIcon(l));
        this.setIconImage(g.getConfig().getLogoMini());
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        this.setLocation(x, y);
        this.labelStatusReading.setVisible(false);
        this.barStatus.setVisible(false);
        properties = g.getEditableProperties();
        refreshTable();
    }
    
    public void refreshPropertyTable(){
        properties = g.getEditableProperties();
        refreshTable();
    }
    
    public void stopLoadingAnimation(){
        this.barStatus.setVisible(false);
        this.barStatus.setIndeterminate(false);
        this.backButton.setEnabled(true);
        this.nextButton.setEnabled(true);
    }
    
    private void refreshTable(){
        tableProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Property", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };
            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Iterator<Entry<String, String>> it = properties.entrySet().iterator();
        while (it.hasNext()) {
            Entry<String,String> currentEntry = it.next();
            Object[] row = new Object[]{currentEntry.getKey(),currentEntry.getValue()};
            ((DefaultTableModel)tableProperties.getModel()).addRow(row);
        }
        
    }
    
    private void deleteSelectedRow(int rowNumber){
        properties.remove((String)tableProperties.getModel().getValueAt(tableProperties.getSelectedRow(), 0));
        ((DefaultTableModel)tableProperties.getModel()).removeRow(rowNumber);
    }
    
    //this method is public so we can access it from the add property form (it simplifies this)
    public void addPropertyRow(String prop, String value){
        //if the property exists, replace it.
        boolean contained = properties.containsKey(prop);
        properties.put(prop, value);
        if(contained){
            //easier than looking for every result...
            refreshTable();
        }else{
            Object[] row = new Object[]{prop,value};
            ((DefaultTableModel)tableProperties.getModel()).addRow(row);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPaneSteps = new javax.swing.JTextPane();
        jSeparator2 = new javax.swing.JSeparator();
        labelTitle = new javax.swing.JLabel();
        labelSteps = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProperties = new javax.swing.JTable();
        loadMetadataFromOnto = new javax.swing.JCheckBox();
        loadMetadataButton = new javax.swing.JButton();
        saveMetadataButton = new javax.swing.JButton();
        addPropButton = new javax.swing.JButton();
        removePropButton = new javax.swing.JButton();
        widocoLogo = new javax.swing.JLabel();
        loadMetadataFromDefaultConfigFile = new javax.swing.JCheckBox();
        barStatus = new javax.swing.JProgressBar();
        labelStatusReading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Step 2: Load the metadata");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        textPaneSteps.setEditable(false);
        textPaneSteps.setContentType("text/html"); // NOI18N
        textPaneSteps.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r \n1. Select template<br/>       \n<b>2. Load Metadata</b><br/>\n3. Load Sections<br/>\n3. Configure LODE<br/>\n5. Generate!\n  </body>\r\n</html>\r\n");
        jScrollPane1.setViewportView(textPaneSteps);

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTitle.setText("Step 2: Load the metadata. Complete the metadata properties.");

        labelSteps.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSteps.setText("Steps");

        tableProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableProperties);

        loadMetadataFromOnto.setText("Load metadata from the ontology URI or file");
        loadMetadataFromOnto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMetadataFromOntoActionPerformed(evt);
            }
        });

        loadMetadataButton.setText("Load from config file...");
        loadMetadataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMetadataButtonActionPerformed(evt);
            }
        });

        saveMetadataButton.setText("Save as config file...");
        saveMetadataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMetadataButtonActionPerformed(evt);
            }
        });

        addPropButton.setText("Add/Edit property");
        addPropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPropButtonActionPerformed(evt);
            }
        });

        removePropButton.setText("Remove property");
        removePropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePropButtonActionPerformed(evt);
            }
        });

        widocoLogo.setText("LOGO");

        loadMetadataFromDefaultConfigFile.setSelected(true);
        loadMetadataFromDefaultConfigFile.setText("Load metadata from default config file");
        loadMetadataFromDefaultConfigFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadMetadataFromDefaultConfigFileActionPerformed(evt);
            }
        });

        labelStatusReading.setText("status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(saveMetadataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1)
                                .addComponent(loadMetadataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(widocoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(loadMetadataFromOnto, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(barStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelStatusReading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(addPropButton)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(removePropButton))
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(loadMetadataFromDefaultConfigFile, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addGap(37, 37, 37)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(widocoLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSteps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loadMetadataButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPropButton)
                        .addComponent(removePropButton))
                    .addComponent(saveMetadataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadMetadataFromOnto)
                            .addComponent(labelStatusReading, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadMetadataFromDefaultConfigFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextButton)
                            .addComponent(backButton)
                            .addComponent(cancelButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.g.saveEditableProperties(this.properties);
        this.g.switchState("back");
    }//GEN-LAST:event_backButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.g.switchState("cancel");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        this.g.saveEditableProperties(this.properties);
        this.g.switchState("next");
    }//GEN-LAST:event_nextButtonActionPerformed

    private void addPropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPropButtonActionPerformed
        AddProperty p = new AddProperty(this);
        p.setVisible(true);
    }//GEN-LAST:event_addPropButtonActionPerformed

    private void removePropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePropButtonActionPerformed
        if(JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete the property?", "Confirm", 
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            while(tableProperties.getSelectedRowCount()>0){
                this.deleteSelectedRow(tableProperties.getSelectedRow());
            }
        }
    }//GEN-LAST:event_removePropButtonActionPerformed

    private void loadMetadataFromOntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMetadataFromOntoActionPerformed
        //TO DO: read ontology and extract basic metadata: author, contributor, title, license.
        if(loadMetadataFromDefaultConfigFile.isSelected() && loadMetadataFromOnto.isSelected()){
            loadMetadataFromDefaultConfigFile.setSelected(false);
        }
        if(loadMetadataFromOnto.isSelected()){
//            JOptionPane.showMessageDialog(null, "TO DO!!");
            this.barStatus.setVisible(true);
            this.barStatus.setIndeterminate(true);
            g.switchState("loadOntologyProperties");
            this.backButton.setEnabled(false);
            this.nextButton.setEnabled(false);
        }
    }//GEN-LAST:event_loadMetadataFromOntoActionPerformed

    private void loadMetadataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMetadataButtonActionPerformed
        //To do: reload the config file from another .properties file.
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
           g.reloadConfiguration(chooser.getSelectedFile().getAbsolutePath());
           this.refreshPropertyTable();
        }
    }//GEN-LAST:event_loadMetadataButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.g.switchState("cancel");
    }//GEN-LAST:event_formWindowClosing

    private void loadMetadataFromDefaultConfigFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadMetadataFromDefaultConfigFileActionPerformed
        // TODO add your handling code here:
        if(loadMetadataFromDefaultConfigFile.isSelected() && loadMetadataFromOnto.isSelected()){
            loadMetadataFromOnto.setSelected(false);
        }
        if(loadMetadataFromDefaultConfigFile.isSelected()){
            //load metadata from the default property file.
            //taken from config
            try{
                URL root = GuiController.class.getProtectionDomain().getCodeSource().getLocation();
                String path = (new File(root.toURI())).getParentFile().getPath();
                g.reloadConfiguration(path+File.separator+TextConstants.configPath);
                this.refreshPropertyTable();
            }catch(URISyntaxException e){
                System.err.println("Error while reading the default config file");
                JOptionPane.showMessageDialog(null, "Error while reading the default .properties file");
            }
        }
        
    }//GEN-LAST:event_loadMetadataFromDefaultConfigFileActionPerformed

    private void saveMetadataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMetadataButtonActionPerformed
        //JOptionPane.showMessageDialog(null, "TO DO!!");
        //se up the out file to be saved: chooser, path, creation.
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showSaveDialog(this);
        //Note: this is not very good. Ideally I should have a method for this,
        //and use it to translate one into the other...
        if(returnVal == JFileChooser.APPROVE_OPTION){
            //create a file (if not exists already
            String path = chooser.getSelectedFile().getAbsolutePath();
            //save the properties in a string
            String textProperties = "\n";//the first line I leave an intro because there have been problems.
            if(properties.get("Ontology Title")!=null){
                textProperties+="title="+properties.get("Ontology Title")+"\n";
            }else{
                textProperties+="title=\n";
            }
            if(properties.get("Ontology Prefix")!=null){
                textProperties+="ontologyPrefix="+properties.get("Ontology Prefix")+"\n";
            }else{
                textProperties+="ontologyPrefix=\n";
            }
            if(properties.get("Ontology Namespace URI")!=null){
                textProperties+="ontologyNamespaceURI="+properties.get("Ontology Namespace URI")+"\n";
            }else{
                textProperties+="ontologyNamespaceURI=\n";
            }
            if(properties.get("This Version")!=null){
                textProperties+="thisVersion="+properties.get("This Version")+"\n";
            }else{
                textProperties+="thisVersion=\n";
            }
            if(properties.get("Latest Version")!=null){
                textProperties+="latestVersion="+properties.get("Latest Version")+"\n";
            }else{
                textProperties+="latestVersion=\n";
            }
            if(properties.get("License URI")!=null){
                textProperties+="licenseURL="+properties.get("License URI")+"\n";
            }else{
                textProperties+="licenseURL=\n";
            }
            if(properties.get("Previous Version")!=null){
                textProperties+="previousVersion="+properties.get("Previous Version")+"\n";
            }else{
                textProperties+="previousVersion=\n";
            }            
            if(properties.get("Date of Release")!=null){
                textProperties+="dateOfRelease="+properties.get("Date of Release")+"\n";
            }else{
                textProperties+="dateOfRelease=\n";
            }
            if(properties.get("Ontology Revision")!=null){
                textProperties+="revision="+properties.get("Ontology Revision")+"\n";
            }else{
                textProperties+="revision=\n";
            }
            if(properties.get("License Name")!=null){
                textProperties+="license="+properties.get("License Name")+"\n";
            }else{
                textProperties+="license=\n";
            }
            if(properties.get("Ontology Name")!=null){
                textProperties+="name="+properties.get("Ontology Name")+"\n";
            }else{
                textProperties+="name=\n";
            }
            if(properties.get("Author")!=null){
                textProperties+="authors="+properties.get("Author")+"\n";
            }else{
                textProperties+="authors=\n";
            }
            if(properties.get("Author URL")!=null){
                textProperties+="authorURL="+properties.get("Author URL")+"\n";
            }else{
                textProperties+="authorURL=\n";
            }
            if(properties.get("Author Institution")!=null){
                textProperties+="authorInstitution="+properties.get("Author Institution")+"\n";
            }else{
                textProperties+="authorInstitution=\n";
            }
            if(properties.get("Contributor")!=null){
                textProperties+="contributors="+properties.get("Contributor")+"\n";
            }else{
                textProperties+="contributors=\n";
            }
            if(properties.get("Contributor URL")!=null){
                textProperties+="contributorsURL="+properties.get("Contributor URL")+"\n";
            }else{
                textProperties+="contributorsURL=\n";
            }
            if(properties.get("Contributor Institution")!=null){
                textProperties+="contributorsInstitution="+properties.get("Contributor Institution")+"\n";
            }else{
                textProperties+="contributorsInstitution=\n";
            }
            if(properties.get("Imported Ontologies Names")!=null){
                textProperties+="importsNames="+properties.get("Imported Ontologies Names")+"\n";
            }else{
                textProperties+="importsNames=\n";
            }
            if(properties.get("Imported Ontologies URIs")!=null){
                textProperties+="importsURLs="+properties.get("Imported Ontologies URIs")+"\n";
            }else{
                textProperties+="importsURLs=\n";
            }
            if(properties.get("Extended Ontologies Names")!=null){
                textProperties+="extendsNames="+properties.get("Extended Ontologies Names")+"\n";
            }else{
                textProperties+="extendsNames=\n";
            }
            if(properties.get("Extended Ontology URLS")!=null){
                textProperties+="extendsURLS="+properties.get("Extended Ontology URLS")+"\n";
            }else{
                textProperties+="extendsURLS=\n";
            }
            if(properties.get("License icon URL")!=null){
                textProperties+="licenseIconURL="+properties.get("License icon URL")+"\n";
            }else{
                textProperties+="licenseIconURL=";
            }
            //copy the result into the file
            Writer writer = null;
            try {
                writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(path), "utf-8"));
                writer.write(textProperties);
            } catch (IOException ex) {
              System.err.println("Error while saving the property file "+ex.getMessage());
            } finally {
               try {
                   writer.close();
               } catch (IOException ex) {}
            }

        }
        
        
    }//GEN-LAST:event_saveMetadataButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GuiStep2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GuiStep2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GuiStep2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GuiStep2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new GuiStep2().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPropButton;
    private javax.swing.JButton backButton;
    private javax.swing.JProgressBar barStatus;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelStatusReading;
    private javax.swing.JLabel labelSteps;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JButton loadMetadataButton;
    private javax.swing.JCheckBox loadMetadataFromDefaultConfigFile;
    private javax.swing.JCheckBox loadMetadataFromOnto;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton removePropButton;
    private javax.swing.JButton saveMetadataButton;
    private javax.swing.JTable tableProperties;
    private javax.swing.JTextPane textPaneSteps;
    private javax.swing.JLabel widocoLogo;
    // End of variables declaration//GEN-END:variables
}
