name: CI

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  maven:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [11, 14, 17]
    steps:
      - uses: actions/checkout@v3
      # details https://github.com/actions/setup-java
      - name: Set up JDK  ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version:  ${{ matrix.jdk }}
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -e --batch-mode package
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: widoco_JDK-${{ matrix.jdk }}
          path: JAR/*.jar
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # https://github.com/docker/metadata-action (lower cases image name, etc.)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@f2a13332ac1ce8c0a71aeac48a150dbb1838ab67
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
